emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/../"
    azure-resource-provider-folder: "resource-manager"
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/PhoenixMassDriver.json"
    use-read-only-status-schema: true
  "@azure-tools/typespec-providerhub-controller":
    emitter-output-dir: "{output-dir}/generated"
    code-kind: model
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
