parameters:
  "service-dir":
    default: "sdk/portalservices"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    output-file: "{azure-resource-provider-folder}/{service-name}/extensions/{version-status}/{version}/extensions.json"
    omit-unreachable-types: true
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.PortalServicesExtension"
    clear-output-folder: true
    model-namespace: true
    namespace: "{package-dir}"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-portalservicesextension"
    namespace: "azure.mgmt.portalservicesextension"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-portalservicesextension"
    namespace: "com.azure.resourcemanager.portalservicesextension"
    service-name: "Portal Services extension"
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "arm-portalservicesextension"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-portalservicesextension"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/portalservicesextension"
    package-dir: "armportalservicesextension"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
