emit:
  - "@azure-tools/typespec-autorest"
parameters:
  "service-dir":
    default: "sdk/arccontainerstorage"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/../resource-manager/Private.ArcContainerStorage/preview/2024-10-01-preview"
    azure-resource-provider-folder: "resource-manager"
    emit-common-types-schema: "never"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag {azure-resource-provider-folder}/{service-name}/{version-status}/{version}/
    arm-resource-flattening: true
    output-file: "arccontainerstorage.json"
    use-read-only-status-schema: true
    omit-unreachable-types: true
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.ArcContainerStorage"
    clear-output-folder: true
    model-namespace: true
    namespace: "{package-dir}"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-arccontainerstorage"
    flavor: "azure"
    namespace: "com.azure.resourcemanager.arccontainerstorage"
    service-name: "ArcContainerStorage"
  "@azure-tools/typespec-ts":
    azureSdkForJs: true
    isModularLibrary: true
    generateMetadata: true
    hierarchyClient: false
    experimental-extensible-enums: true
    enableOperationGroup: true
    package-dir: "arm-arccontainerstorage"
    flavor: "azure"
    package-details:
      name: "@azure/arm-arccontainerstorage"
  "@azure-tools/typespec-python":
    namespace: "azure.mgmt.arccontainerstorage"
    package-dir: "azure-mgmt-arccontainerstorage"
    package-name: "{package-dir}"
    flavor: "azure"
    generate-test: true
    generate-sample: true
    api-version: "2024-10-01-preview"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/arccontainerstorage"
    package-dir: "armarccontainerstorage"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    flavor: "azure"
    fix-const-stuttering: true
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
