parameters:
  "service-dir":
    default: "sdk/discovery-catalog"
  "service-directory-name":
    default: "discovery-catalog"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/.."
    omit-unreachable-types: false
    output-file: "{azure-resource-provider-folder}/Microsoft.Discovery.Catalog/{version-status}/{version}/discovery-catalog.json"
    azure-resource-provider-folder: "data-plane"
    emit-lro-options: "none"
  #  "@azure-tools/typespec-python":
  #    package-pprint-name: '"Azure Discovery Catalog"'
  #    package-version: 4.12.0b1
  #    package-dir: "azure-discovery-catalog"
  #    package-name: "{package-dir}"
  #    emitter-output-dir: "{project-root}/{service-dir}/{package-name}"
  #    flavor: azure
  #    generate-test: true
  #    generate-sample: true
  #  # Uncomment this line and add "@azure-tools/typespec-csharp" to your package.json to generate C# code
  #  "@azure-tools/typespec-csharp":
  #    package-dir: Azure.Discovery.Catalog
  #    model-namespace: false
  #    namespace: Microsoft.Discovery.Catalog
  #    flavor: azure
  #    api-version: "2018-01-01"
  "@azure-tools/typespec-ts":
    generateMetadata: true
    generateTest: false
    azureSdkForJs: true
    experimentalExtensibleEnums: true
    package-dir: "discovery-catalog"
    packageDetails:
      name: "@azure/discovery-catalog"
    flavor: azure
    isModularLibrary: true
#  "@azure-tools/typespec-go":
#    module: "github.com/Azure/azure-sdk-for-go/sdk/discovery-catalog"
#    module-version: "0.0.1"
#    emitter-output-dir: "{project-root}"
#  "@azure-tools/typespec-java":
#    emitter-output-dir: "{project-root}"
#    namespace: com.azure.discovery.catalog
#    #    models-subpackage: systemevents
#    package-dir: azure-discovery-catalog
#    #    customization-class: customization/src/main/java/EventGridSystemEventsCustomization.java
#    #    custom-types-subpackage: implementation.models
#    #    custom-types: AcsRouterCommunicationError,AcsMessageChannelEventError
#    flavor: azure
#    dev-options:
#      loglevel: info
