emit:
  - '@azure-tools/typespec-autorest'
options:
  '@azure-tools/typespec-autorest':
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/"
    azure-resource-provider-folder: "../resource-manager"
    new-line: lf
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
