emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    examples-directory: "{project-root}/examples"
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/throttling.json"
    include-x-typespec-name: inline-only
    use-read-only-status-schema: true
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
