parameters:
  "service-dir":
    default: "sdk/healthcareinterop"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}"
    azure-resource-provider-folder: "resource-manager"
    output-file: "{version-status}/{version}/Cloud.json"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
  "@azure-tools/typespec-csharp":
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
    flavor: azure
    clear-output-folder: true
    model-namespace: true
    namespace: "Azure.ResourceManager.PrvtHealthcareInteropDev.Cloud"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-prvthealthcareinteropdev-cloud"
    namespace: "azure.mgmt.prvthealthcareinteropdev.cloud"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-prvthealthcareinteropdevcloud"
    namespace: "com.azure.resourcemanager.prvthealthcareinteropdev.cloud"
    service-name: "cloud"
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "arm-prvthealthcareinteropdev-cloud"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-prvthealthcareinteropdevcloud"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/prvthealthcareinteropdevcloud"
    emitter-output-dir: "{output-dir}/{service-dir}/armprvthealthcareinteropdevcloud"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armprvthealthcareinteropdevcloud"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
