parameters:
  "service-dir":
    default: "sdk/extmanagedoperations"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/extmanagedoperations.json"
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.Poc360"
    clear-output-folder: true
    model-namespace: true
    namespace: "{package-dir}"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-extmanagedoperations"
    namespace: "azure.mgmt.extmanagedoperations"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-ts":
    package-dir: "arm-extmanagedoperations"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-extmanagedoperations"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/extmanagedoperations"
    package-dir: "armextmanagedoperations"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-extmanagedoperations"
    namespace: "com.azure.resourcemanager.extmanagedoperations"
    service-name: "ExtManagedOperations"
    flavor: "azure"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
