emit:
  - '@azure-tools/typespec-autorest'
  - '@azure-tools/typespec-autorest-canonical'
options:
  '@azure-tools/typespec-autorest':
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    examples-directory: "{project-root}/examples"
    use-read-only-status-schema: true
  '@azure-tools/typespec-autorest-canonical':
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
