output-dir: "{project-root}/../"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{output-dir}"
    azure-resource-provider-folder: resource-manager
    output-file: "{azure-resource-provider-folder}/Private.StorageDataManagementRP/storageDataManagement/{version-status}/{version}/StorageDataRP.json"
    new-line: lf
    use-read-only-status-schema: true
    examples-dir: "{project-root}/examples/"
  "@azure-tools/typespec-providerhub-controller":
    emitter-output-dir: "{output-dir}/generated"
    code-kind: model
    include-operation-controller: false
    include-cancellation-token: true
    include-subscription-lifecycle-controller: true
    include-versioning-classes: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
