parameters:
  "service-dir":
    default: "sdk/healthcareinterop"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/cloud/{version-status}/{version}/cloud.json"
  "@azure-tools/typespec-csharp":
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
    flavor: azure
    package-dir: "Azure.ResourceManager.PrvtHealthcareInteropInt.Cloud"
    clear-output-folder: true
    model-namespace: true
    namespace: "Azure.ResourceManager.PrvtHealthcareInteropInt.Cloud"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-prvthealthcareinteropint-cloud"
    namespace: "azure.mgmt.prvthealthcareinteropint.cloud"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-prvthealthcareinteropint-cloud"
    namespace: "com.azure.resourcemanager.prvthealthcareinteropint.cloud"
    service-name: "cloud"
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "arm-prvthealthcareinteropint-cloud"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-prvthealthcareinteropintcloud"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/prvthealthcareinteropintcloud"
    emitter-output-dir: "{output-dir}/{service-dir}/armprvthealthcareinteropintcloud"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armprvthealthcareinteropintcloud"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
