parameters:
  "service-dir":
    default: "sdk/privatehealthcareinteropint"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/cloud/{version-status}/{version}/cloud.json"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-privatehealthcareinteropint"
    namespace: "com.azure.resourcemanager.privatehealthcareinteropint"
    service-name: "cloud"
    flavor: azure
  "@azure-tools/typespec-ts":
    experimental-extensible-enums: true
    package-dir: "arm-privatehealthcareinteropint"
    package-details:
      name: "@azure/arm-privatehealthcareinteropint"
    flavor: azure
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/privatehealthcareinteropint"
    package-dir: "armprivatehealthcareinteropint"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-privatehealthcareinteropint"
    namespace: "azure.mgmt.privatehealthcareinteropint"
    generate-sample: true
    generate-test: true
    flavor: azure
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.ResourceManager.PrivateHealthcareInteropInt"
    namespace: "{package-dir}"
    clear-output-folder: true
    flavor: azure
  "@azure-tools/typespec-client-generator-cli":
    additionalDirectories:
      - "specification/healthcareinterop/Private.HealthcareInteropInt.Edge.Management/"
