emit:
  - '@azure-tools/typespec-autorest'
  - '@typespec/openapi3'

options:
  '@azure-tools/typespec-autorest':
    arm-types-dir: "../../../../../common-types/resource-management"
    use-read-only-status-schema: true
