emit:
  - "@azure-tools/typespec-autorest"
parameters:
  service-dir:
    default: "sdk/changecontrol"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/ChangeControl/{version-status}/{version}/ChangeControl.json"
  "@azure-tools/typespec-java":
    flavor: azure
    package-dir: "azure-resourcemanager-changecontrol"
    namespace: "com.azure.resourcemanager.changecontrol"
  "@azure-tools/typespec-ts":
    flavor: azure
    experimental-extensible-enums: true
    package-dir: "arm-changecontrol"
    package-details:
      name: "@azure/arm-changecontrol"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/changecontrol"
    package-dir: "armchangecontrol"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-python":
    flavor: azure
    package-dir: "azure-mgmt-changecontrol"
    namespace: "azure.mgmt.changecontrol"
    generate-sample: true
    generate-test: true
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.ChangeControl"
    namespace: "{package-dir}"
    clear-output-folder: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
