parameters:
  "service-dir":
    default: "sdk/applicationmigration"
emit:
  - "@azure-tools/typespec-autorest"
output-dir: "{project-root}/../../"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{output-dir}"
    output-file: "{azure-resource-provider-folder}/{service-name}/ApplicationMigration/{version-status}/{version}/codescansites.json"
    azure-resource-provider-folder: ./resource-manager
    use-read-only-status-schema: true
    arm-types-dir: "{project-root}/../../../common-types/resource-management"
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.ApplicationMigration"
    clear-output-folder: true
    model-namespace: true
    namespace: "{package-dir}"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-applicationmigration"
    package-name: "{package-dir}"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-applicationmigration"
    namespace: "com.azure.resourcemanager.applicationmigration"
    service-name: "applicationmigration"
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "arm-applicationmigration"
    is-modular-library: true
    flavor: "azure"
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-applicationmigration"