emit:
  - "@azure-tools/typespec-autorest" # This generates the swagger / openapi v2 file

# Variables in use:
# {project-root} - parent directory of tspconfig.yaml
# {output-dir} - correspond to --output-path in tsp.js compile command
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    azure-resource-provider-folder: "resource-manager"
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/AppSecurity.json"

linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
