output-dir: "{project-root}/../"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{output-dir}"
    azure-resource-provider-folder: resource-manager
    examples-dir: "{project-root}/examples"
    use-read-only-status-schema: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
