output-dir: "{project-root}/../"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{output-dir}"
    azure-resource-provider-folder: ./swagger/Approvals/resource-manager
    examples-dir: "{project-root}/examples"
    new-line: lf
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
