output-dir: "{project-root}/../"
emit:
  - "@azure-tools/typespec-autorest"
  - "@azure-tools/typespec-providerhub-controller"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{output-dir}"
    azure-resource-provider-folder: ./swagger/SustainabilityServices/resource-manager
    examples-directory: ./examples
    new-line: lf
    use-read-only-status-schema: true
  "@azure-tools/typespec-providerhub-controller":
    emitter-output-dir: "{output-dir}/generated"
    code-kind: model
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
    - "@azure-tools/typespec-azure-resource-manager/all"