output-dir: "{project-root}/.."
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{output-dir}"
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/Microsoft.Access/{version-status}/{version}/openapi.json"
    arm-types-dir: ../../../../../common-types/resource-management
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
