emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    examples-dir: "{project-root}/examples"
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/Private.AiForScience/{version-status}/{version}/science.json"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
