emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-python":
    flavor: azure
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-applink"
    namespace: "azure.mgmt.applink"
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-applink"
    flavor: azure
    namespace: "com.azure.resourcemanager.applink"
    service-name: "applink"
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-applink"
    experimental-extensible-enums: true
    flavor: azure
    package-details:
      name: "@azure/arm-applink"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/applink"
    emitter-output-dir: "{output-dir}/{service-dir}/armapplink"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armapplink"
    fix-const-stuttering: true
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
parameters:
  service-dir:
    default: sdk/placeholder
