parameters:
  "service-dir":
    default: "sdk/portalservices"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/settings/{version-status}/{version}/settings.json"
    omit-unreachable-types: true

  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.PortalServicesTenant"
    clear-output-folder: true
    model-namespace: true
    namespace: "{package-dir}"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-portalservicestenant"
    namespace: "azure.mgmt.portalservicestenant"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-portalservicestenant"
    namespace: "com.azure.resourcemanager.portalservicestenant"
    service-name: "Portal Services Tenant"
    flavor: azure
  "@azure-tools/typespec-ts":
    package-dir: "arm-portalservicestenant"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-portalservicestenant"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/portalservicestenant"
    package-dir: "armportalservicestenant"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
