options:
   "@azure-tools/typespec-autorest":
      emitter-output-dir: "{cwd}/../resource-manager/Microsoft.FootprintMonitoring/preview/2024-07-10-preview"
      azure-resource-provider-folder: "resource-manager"