output-dir: "{project-root}/../"
emit:
  - "@azure-tools/typespec-autorest"
  - "@azure-tools/typespec-providerhub-controller"
  - " build " # used when running dotnet build typespec.csproj
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{output-dir}"
    azure-resource-provider-folder: ./swagger/csol/resource-manager
    examples-directory: ./examples
    new-line: lf
  "@azure-tools/typespec-providerhub-controller":
    emitter-output-dir: "{output-dir}/generated"
    code-kind: model
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
