output-dir: "{project-root}/../"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{output-dir}/../"
    azure-resource-provider-folder: "resource-manager"
    new-line: lf
    arm-types-dir: "{project-root}/../../../common-types/resource-management"
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
