parameters:
  "service-dir":
    default: "sdk/private.healthcareInterop.dev.cloud"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/edge/{version-status}/{version}/edge.json"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-privatehealthcareinteropdev"
    namespace: "com.azure.resourcemanager.privatehealthcareinteropdev"
    service-name: "edge"
    flavor: azure
  "@azure-tools/typespec-ts":
    experimental-extensible-enums: true
    package-dir: "arm-privatehealthcareinteropdev"
    package-details:
      name: "@azure/arm-privatehealthcareinteropdev"
    flavor: azure
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/healthcareinteropdev"
    package-dir: "armprivatehealthcareinteropdev"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-privatehealthcareinteropdev"
    namespace: "azure.mgmt.privatehealthcareinteropdev"
    generate-sample: true
    generate-test: true
    flavor: azure
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.ResourceManager.PrivateHealthcareInteropDev"
    namespace: "{package-dir}"
    clear-output-folder: true
    flavor: azure
