parameters:
  "service-dir":
    default: "sdk/throttling"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    arm-types-dir: "../../../../../common-types/resource-management"
    azure-resource-provider-folder: "resource-manager"
    emitter-output-dir: "{project-root}/.."
    examples-dir: "{project-root}/examples"
    include-x-typespec-name: inline-only
    omit-unreachable-types: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/throttling.json"
    use-read-only-status-schema: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
