parameters:
  "service-dir":
    default: "sdk/quantum"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: false
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file:
      "{azure-resource-provider-folder}/{service-name}/{version-status}/\
      {version}/quantum.json"
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-quantum"
    package-name: "{package-dir}"
    flavor: "azure"
    generate-test: true
    generate-sample: true
    namespace: azure.mgmt.placeholder #!!!IMPORTANT!!! To ensure the emitter correctly produces SDK, this configuration is added by Azure SDK Team. Some configurations use placeholder values. For modifications, please refer to https://aka.ms/azsdk/specs/typespec-validation#sdktspconfigvalidation
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-quantum"
    namespace: "com.azure.resourcemanager.quantum"
    service-name: "quantum"
    flavor: azure
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/quantum"
    package-dir: "armquantum"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-examples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    remove-unreferenced-types: true
    generate-samples: true #!!!IMPORTANT!!! To ensure the emitter correctly produces SDK, this configuration is added by Azure SDK Team. Some configurations use placeholder values. For modifications, please refer to https://aka.ms/azsdk/specs/typespec-validation#sdktspconfigvalidation
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.ResourceManager.Quantum"
    flavor: azure
    clear-output-folder: true
    model-namespace: false
    namespace: "{package-dir}"
  "@azure-tools/typespec-ts":
    package-dir: "arm-quantum"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-quantum"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
