emit:
  - "@azure-tools/typespec-autorest"
  - "@azure-tools/typespec-python"
  - "@azure-tools/typespec-java"
  - "@azure-tools/typespec-csharp"
  - "@azure-tools/typespec-ts"
  - "@azure-tools/typespec-go"

options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/deviceregistry.json"
    examples-dir: "{project-root}/examples"
    use-read-only-status-schema: true

  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-deviceregistry"
    emitter-output-dir: "{project-root}/../../../sdk/deviceregistry/azure-mgmt-deviceregistry"
    package-name: "{package-dir}"
    flavor: azure

  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-deviceregistry"
    emitter-output-dir: "{project-root}/../../../sdk/deviceregistry/{package-dir}"
    namespace: "com.azure.resourcemanager.deviceregistry"
    flavor: azure

  "@azure-tools/typespec-csharp":
    package-dir: "Azure.ResourceManager.DeviceRegistry"
    emitter-output-dir: "{project-root}/../../../sdk/deviceregistry/{package-dir}"
    namespace: "{package-dir}"
    flavor: azure
    clear-output-folder: true

  "@azure-tools/typespec-ts":
    package-dir: "arm-deviceregistry"
    emitter-output-dir: "{project-root}/../../../sdk/deviceregistry/{package-dir}"
    packageDetails:
      name: "@azure/arm-deviceregistry"
    flavor: azure
    generateMetadata: true
    isModularLibrary: true

  "@azure-tools/typespec-go":
    package-dir: "armdeviceregistry"
    emitter-output-dir: "{project-root}/../../../sdk/resourcemanager/deviceregistry/{package-dir}"
    module: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/deviceregistry/{package-dir}"
    flavor: azure
    generateMetadata: true
    head-as-boolean: true

parameters:
  service-dir:
    default: "sdk/resourcemanager/deviceregistry"

linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"